export type RoadmapGroup={title:string;description:string;items:string[]};
export type RoadmapModule={slug:string;number:string;title:string;eyebrow:string;summary:string;image:string;groups:RoadmapGroup[]};

export const roadmapModules:RoadmapModule[]=[
 {slug:"khong-gian-van-hoa-nghe-thuat",number:"01",title:"Không gian văn hóa — nghệ thuật",eyebrow:"Bản sắc Việt trong đời sống đương đại",summary:"Khám phá biểu diễn, làng nghề, triển lãm, không gian văn hóa và những trải nghiệm dành cho gia đình.",image:"/images/ciic/demo/khong-gian-van-hoa.webp",groups:[
  {title:"Biểu diễn nghệ thuật",description:"Sân khấu gần gũi, đa dạng vùng miền.",items:["Acoustic và nhạc sống","Dân ca — nhạc truyền thống","Sân khấu dân gian ba miền","Múa, thời trang và trình diễn đường phố"]},
  {title:"Làng nghề & workshop",description:"Gặp gỡ nghệ nhân và tự tay trải nghiệm.",items:["Làng nghề truyền thống","Thủ công mỹ nghệ","Workshop nghệ thuật — ẩm thực","Trải nghiệm di sản"]},
  {title:"Triển lãm & không gian văn hóa",description:"Câu chuyện văn hóa được kể bằng nhiều hình thức.",items:["Tranh ảnh và tác phẩm nghệ thuật","Cây Văn hóa Việt Nam","Sài Gòn xưa và nay","Chim, hoa, cá cảnh"]},
  {title:"Sáng tạo trẻ em",description:"Vui chơi, khám phá và học qua trải nghiệm.",items:["Trò chơi dân gian","Nghệ thuật và thủ công","Ngày hội theo chủ đề","Bộ sưu tập ảnh — video"]},
 ]},
 {slug:"cong-dong-hoc-tap-sang-tao",number:"02",title:"Cộng đồng học tập & sáng tạo",eyebrow:"Học tập suốt đời — sáng tạo mỗi ngày",summary:"Các lớp nghệ thuật, kỹ năng sống, công nghệ và nghề nghiệp dành cho nhiều nhóm tuổi.",image:"/images/ciic/demo/cong-dong-hoc-tap.webp",groups:[
  {title:"Các môn nghệ thuật",description:"Nuôi dưỡng cảm xúc và khả năng biểu đạt.",items:["Âm nhạc và nhạc cụ","Ca hát","Hội họa","Khiêu vũ","Đờn ca tài tử"]},
  {title:"Nghệ thuật biểu diễn",description:"Tự tin trước công chúng và làm chủ sân khấu.",items:["MC","Dancer","Kỹ năng biểu diễn","Giao tiếp trước công chúng"]},
  {title:"Kỹ năng sống & an toàn",description:"Kiến thức thiết thực cho gia đình và cộng đồng.",items:["Phòng chống đuối nước","Kỹ năng sống","An toàn cộng đồng","Chương trình theo độ tuổi"]},
  {title:"Tin học, AI & nghề nghiệp",description:"Làm quen công cụ mới và kết nối cơ hội.",items:["Tin học cơ bản","Ứng dụng công nghệ AI","Kỹ năng số","Khởi nghiệp và mentoring"]},
 ]},
 {slug:"trien-lam-hoi-cho-giao-thuong",number:"03",title:"Triển lãm — hội chợ — giao thương",eyebrow:"Trưng bày sản phẩm — mở rộng kết nối",summary:"Không gian cho phiên chợ, gian hàng, hội nghị, kết nối B2B và xúc tiến thương mại.",image:"/images/ciic/demo/trien-lam-giao-thuong.webp",groups:[
  {title:"Triển lãm & hội chợ",description:"Giới thiệu sản phẩm theo chủ đề.",items:["Triển lãm chuyên đề","Hội chợ văn hóa — sáng tạo","Phiên chợ cộng đồng và OCOP","Gian hàng trải nghiệm"]},
  {title:"Kết nối B2B",description:"Kết nối doanh nghiệp, đối tác và khách hàng.",items:["Hồ sơ doanh nghiệp","Danh mục sản phẩm — dịch vụ","Gặp gỡ đối tác","Kết nối cung — cầu"]},
  {title:"Hội nghị & xúc tiến",description:"Tổ chức chương trình chuyên nghiệp.",items:["Hội nghị và tọa đàm","Pitching","Ra mắt sản phẩm","Tài liệu sự kiện"]},
  {title:"Quản lý gian hàng",description:"Thông tin rõ ràng từ đăng ký đến bàn giao.",items:["Vị trí và diện tích","Giá thuê và tiện ích","Hồ sơ xét duyệt","Theo dõi trạng thái"]},
 ]},
 {slug:"cong-nghe-noi-dung-so",number:"04",title:"Công nghệ & nội dung số",eyebrow:"Hạ tầng sáng tạo cho cộng đồng",summary:"Studio, thiết bị, thư viện số và các trải nghiệm ứng dụng công nghệ trong sáng tạo.",image:"/images/ciic/demo/cong-nghe-noi-dung-so.webp",groups:[
  {title:"Sản xuất nội dung",description:"Không gian dành cho cá nhân và đội nhóm.",items:["Phòng thu âm","Quay phim — chụp ảnh","Podcast","Livestream và phỏng vấn"]},
  {title:"Dịch vụ công nghệ",description:"Đặt lịch studio, thiết bị và hỗ trợ kỹ thuật.",items:["Đặt lịch studio","Thuê thiết bị","Hỗ trợ sản xuất","Quản lý chi phí"]},
  {title:"Thư viện nội dung số",description:"Lưu giữ và lan tỏa câu chuyện CIIC.",items:["Video và podcast","Câu chuyện di sản","Nghệ nhân và sản phẩm","Nội dung sau sự kiện"]},
  {title:"Sáng tạo số & AI",description:"Trải nghiệm công cụ sáng tạo mới.",items:["Ứng dụng AI","Nội dung tương tác","Trưng bày sản phẩm số","Bản quyền và quyền xuất bản"]},
 ]},
 {slug:"the-duc-the-thao",number:"05",title:"Thể dục thể thao",eyebrow:"Vận động khỏe — kết nối vui",summary:"Môn thể thao, booking sân tập, lịch thi đấu và sự kiện vận động trong một điểm đến.",image:"/images/ciic/demo/the-duc-the-thao.webp",groups:[
  {title:"Môn thể thao",description:"Mỗi môn được phát triển thành trang thông tin riêng.",items:["Pickleball","Tennis","Bơi lội","Bowling","Bóng chuyền","Cầu mây","Cầu lông","Bắn cung"]},
  {title:"Booking & dịch vụ",description:"Tra cứu và gửi yêu cầu nhanh chóng.",items:["Sân tập","Địa điểm tổ chức sự kiện","Thiết bị và huấn luyện","Dịch vụ hỗ trợ khác"]},
  {title:"Lịch thi đấu",description:"Theo dõi hoạt động theo môn và thời gian.",items:["Giải đấu","Giao lưu","Ngày hội vận động","Kết quả và thông báo"]},
  {title:"Sự kiện & activities",description:"Hoạt động cộng đồng cho mọi lứa tuổi.",items:["Đăng ký tham dự","Đăng ký thi đấu","Chương trình trải nghiệm","Hoạt động gia đình"]},
 ]},
 {slug:"lich-hoat-dong",number:"06",title:"Lịch hoạt động",eyebrow:"Biết trước lịch — chủ động tham gia",summary:"Lịch tổng hợp lớp học, biểu diễn, thi đấu, workshop và sự kiện theo ngày, tuần hoặc tháng.",image:"/images/ciic/demo/khong-gian-van-hoa.webp",groups:[{title:"Lịch hôm nay",description:"Các hoạt động demo đang chờ lịch chính thức.",items:["08:00 — Lớp kỹ năng số","15:00 — Workshop thủ công","18:30 — Giao lưu thể thao"]},{title:"Cuối tuần",description:"Hoạt động dành cho gia đình.",items:["Sân khấu cộng đồng","Phiên chợ sáng tạo","Ngày hội trẻ em"]},{title:"Theo dõi lịch",description:"Lọc theo nhu cầu cá nhân.",items:["Theo chủ đề","Theo độ tuổi","Theo địa điểm","Theo hình thức tham gia"]}]},
 {slug:"booking-dang-ky",number:"07",title:"Booking & đăng ký",eyebrow:"Gửi yêu cầu trong vài bước",summary:"Đăng ký lớp học, workshop, sự kiện hoặc gửi yêu cầu đặt sân, địa điểm và dịch vụ.",image:"/images/ciic/demo/the-duc-the-thao.webp",groups:[{title:"Đăng ký hoạt động",description:"Dành cho cá nhân và gia đình.",items:["Lớp học","Workshop","Giải đấu","Hội nghị — sự kiện"]},{title:"Đặt không gian",description:"Dành cho CLB, doanh nghiệp và đối tác.",items:["Sân tập","Studio","Phòng hội nghị","Gian hàng"]},{title:"Theo dõi yêu cầu",description:"Quy trình demo trước khi mở tài khoản thành viên.",items:["Tiếp nhận","Xác nhận","Nhắc lịch","Hoàn thành"]}]},
 {slug:"dia-diem-ban-do",number:"08",title:"Địa điểm & bản đồ CIIC",eyebrow:"Tìm đúng nơi — đến đúng giờ",summary:"Khám phá các khu vực, tiện ích, lối đi và thông tin liên hệ tại CIIC Tân Sơn Nhất.",image:"/images/ciic/image93.webp",groups:[{title:"Khu văn hóa",description:"Biểu diễn, triển lãm và workshop.",items:["Sân khấu","Khu trưng bày","Làng nghề","Khu trẻ em"]},{title:"Khu thể thao",description:"Các sân và khu luyện tập.",items:["Sân đa năng","Khu bơi lội","Khu thể thao trong nhà","Khu dịch vụ"]},{title:"Tiện ích",description:"Hỗ trợ hành trình tham quan.",items:["Bãi xe","Quầy thông tin","Khu ẩm thực","Lối tiếp cận thuận tiện"]}]},
 {slug:"tin-tuc-cau-chuyen",number:"09",title:"Tin tức & câu chuyện CIIC",eyebrow:"Những điều đang diễn ra tại CIIC",summary:"Tin hoạt động, câu chuyện nghệ nhân, đối tác, cộng đồng và các chương trình sắp tới.",image:"/images/ciic/demo/trien-lam-giao-thuong.webp",groups:[{title:"Tin hoạt động",description:"Cập nhật từ các chương trình.",items:["Thông báo mới","Lịch sắp diễn ra","Kết quả hoạt động","Thay đổi lịch"]},{title:"Câu chuyện CIIC",description:"Con người tạo nên giá trị.",items:["Nghệ nhân","Huấn luyện viên","Người học","Đối tác cộng đồng"]},{title:"Tài nguyên truyền thông",description:"Nội dung dành cho báo chí và đối tác.",items:["Thông cáo","Hình ảnh","Video","Tài liệu giới thiệu"]}]},
 {slug:"tai-khoan-thanh-vien",number:"10",title:"Tài khoản & thành viên",eyebrow:"Một nơi quản lý mọi hoạt động",summary:"Khu vực dự kiến giúp thành viên xem lịch sử đăng ký, booking, thông báo và quyền lợi cá nhân.",image:"/images/ciic/demo/cong-dong-hoc-tap.webp",groups:[{title:"Hồ sơ thành viên",description:"Thông tin và nhu cầu quan tâm.",items:["Thông tin cá nhân","Nhóm tuổi","Chủ đề yêu thích","Đồng ý nhận tin"]},{title:"Hoạt động của tôi",description:"Theo dõi thuận tiện.",items:["Lịch đã đăng ký","Booking đã gửi","Danh sách chờ","Nhắc lịch"]},{title:"Quyền lợi",description:"Mở rộng ở giai đoạn tiếp theo.",items:["Vé điện tử","QR check-in","Điểm thưởng","Ưu đãi đối tác"]}]},
];

export const roadmapBySlug=Object.fromEntries(roadmapModules.map(item=>[item.slug,item]));
export const sportsSlugs={"pickleball":"Pickleball","tennis":"Tennis","boi-loi":"Bơi lội","bowling":"Bowling","bong-chuyen":"Bóng chuyền","cau-may":"Cầu mây","cau-long":"Cầu lông","ban-cung":"Bắn cung"} as const;
