import { resendStatus } from "@/lib/resend";

export const dynamic="force-dynamic";
export default function IntegrationsPage(){
  const imageKit={configured:Boolean(process.env.IMAGEKIT_PRIVATE_KEY&&process.env.IMAGEKIT_PUBLIC_KEY&&process.env.IMAGEKIT_URL_ENDPOINT),endpoint:process.env.IMAGEKIT_URL_ENDPOINT||""};
  const resend=resendStatus();
  return <><div className="admin-page-heading"><div><span>Hệ thống</span><h1>Tích hợp dịch vụ</h1><p>Kiểm tra kết nối lưu trữ ảnh và email thông báo của website CIIC.</p></div></div><div className="integration-grid">
    <section className="integration-card"><div className="integration-title"><div><span className="integration-logo imagekit">IK</span><div><h2>ImageKit</h2><p>Upload và phân phối hình ảnh</p></div></div><b className={imageKit.configured?"status-ok":"status-off"}>{imageKit.configured?"Đã kết nối":"Chưa cấu hình"}</b></div><dl><div><dt>URL endpoint</dt><dd>{imageKit.endpoint||"Chưa có"}</dd></div><div><dt>Public key</dt><dd>{process.env.IMAGEKIT_PUBLIC_KEY?"Đã thiết lập":"Chưa có"}</dd></div><div><dt>Private key</dt><dd>{process.env.IMAGEKIT_PRIVATE_KEY?"Đã thiết lập an toàn trên Vercel":"Chưa có"}</dd></div></dl><p className="integration-note">Nút Upload trong Cấu hình, Chương trình, Bài viết và Kho ảnh sử dụng kết nối này. File được lưu trong thư mục <code>ciic/</code>.</p></section>
    <section className="integration-card"><div className="integration-title"><div><span className="integration-logo resend">R</span><div><h2>Resend</h2><p>Email thông báo đăng ký mới</p></div></div><b className={resend.configured?"status-ok":"status-off"}>{resend.configured?"Đã kết nối":"Chưa cấu hình"}</b></div><dl><div><dt>Email gửi</dt><dd>{resend.from||"Chưa có"}</dd></div><div><dt>Email nhận</dt><dd>{resend.to||"Chưa có"}</dd></div><div><dt>API key</dt><dd>{process.env.RESEND_API_KEY?"Đã thiết lập an toàn trên Vercel":"Chưa có"}</dd></div></dl><p className="integration-note">Khi có đăng ký mới, dữ liệu vẫn được lưu vào MongoDB và hệ thống đồng thời gửi email thông báo qua Resend.</p></section>
  </div><section className="integration-help"><h2>Biến môi trường cần thiết</h2><code>IMAGEKIT_PRIVATE_KEY · IMAGEKIT_PUBLIC_KEY · IMAGEKIT_URL_ENDPOINT</code><code>RESEND_API_KEY · RESEND_FROM_EMAIL · RESEND_TO_EMAIL</code><p>Khóa bí mật chỉ được cấu hình trong Vercel, không hiển thị và không lưu vào MongoDB/GitHub.</p></section></>;
}
