import { resendStatus } from "@/lib/resend";

export const dynamic="force-dynamic";
export default function IntegrationsPage(){
  const imageKit={configured:Boolean(process.env.IMAGEKIT_PRIVATE_KEY&&process.env.IMAGEKIT_PUBLIC_KEY&&process.env.IMAGEKIT_URL_ENDPOINT),endpoint:process.env.IMAGEKIT_URL_ENDPOINT||""};
  const resend=resendStatus();
  return <><div className="admin-page-heading"><div><span>Kết nối dịch vụ</span><h1>Ảnh và email thông báo</h1><p>Theo dõi nơi lưu ảnh và hộp thư nhận đăng ký mới của CIIC.</p></div></div><div className="integration-grid">
    <section className="integration-card"><div className="integration-title"><div><span className="integration-logo imagekit">IK</span><div><h2>Kho ảnh ImageKit</h2><p>Lưu và hiển thị hình ảnh trên website</p></div></div><b className={imageKit.configured?"status-ok":"status-off"}>{imageKit.configured?"Đang hoạt động":"Cần bổ sung"}</b></div><dl><div><dt>Địa chỉ kho ảnh</dt><dd>{imageKit.endpoint||"Chưa thiết lập"}</dd></div><div><dt>Quyền tải ảnh</dt><dd>{process.env.IMAGEKIT_PUBLIC_KEY?"Đã sẵn sàng":"Chưa thiết lập"}</dd></div><div><dt>Bảo mật kho ảnh</dt><dd>{process.env.IMAGEKIT_PRIVATE_KEY?"Đã được bảo vệ":"Chưa thiết lập"}</dd></div></dl><p className="integration-note">Bạn có thể dùng nút “Tải ảnh” khi chỉnh sửa trang chủ, chương trình, bài viết và kho ảnh.</p></section>
    <section className="integration-card"><div className="integration-title"><div><span className="integration-logo resend">R</span><div><h2>Email Resend</h2><p>Báo ngay khi có người đăng ký mới</p></div></div><b className={resend.configured?"status-ok":"status-off"}>{resend.configured?"Đang hoạt động":"Cần bổ sung"}</b></div><dl><div><dt>Địa chỉ gửi</dt><dd>{resend.from||"Chưa thiết lập"}</dd></div><div><dt>Địa chỉ nhận</dt><dd>{resend.to||"Chưa thiết lập"}</dd></div><div><dt>Quyền gửi email</dt><dd>{process.env.RESEND_API_KEY?"Đã được bảo vệ":"Chưa thiết lập"}</dd></div></dl><p className="integration-note">Mỗi khi có đăng ký mới, thông tin sẽ được lưu trong mục “Đăng ký” và gửi thêm một email thông báo.</p></section>
  </div><section className="integration-help"><h2>Thông tin dành cho người cài đặt</h2><code>IMAGEKIT_PRIVATE_KEY · IMAGEKIT_PUBLIC_KEY · IMAGEKIT_URL_ENDPOINT</code><code>RESEND_API_KEY · RESEND_FROM_EMAIL · RESEND_TO_EMAIL</code><p>Các mã bảo mật được lưu riêng trên Vercel và không xuất hiện trong khu vực quản lý.</p></section></>;
}
