import { AdminManager, type AdminField } from "@/components/admin/manager";
import { getSettings } from "@/lib/content";

const fields:AdminField[]=[
  {name:"siteName",label:"Tên website",section:"Nhận diện thương hiệu"},{name:"shortName",label:"Tên ngắn",section:"Nhận diện thương hiệu"},{name:"slogan",label:"Slogan",section:"Nhận diện thương hiệu"},{name:"logoUrl",label:"Logo CIIC",type:"image",section:"Nhận diện thương hiệu"},
  {name:"heroImage",label:"Banner chính",type:"image",section:"Trang chủ · Banner"},{name:"heroEyebrow",label:"Dòng nhỏ",section:"Trang chủ · Banner"},{name:"heroTitle",label:"Tiêu đề",type:"textarea",section:"Trang chủ · Banner"},{name:"heroSubtitle",label:"Mô tả",type:"textarea",section:"Trang chủ · Banner"},
  {name:"aboutTitle",label:"Tiêu đề giới thiệu",type:"textarea",section:"Trang chủ · Giới thiệu"},{name:"aboutBody",label:"Nội dung giới thiệu",type:"textarea",section:"Trang chủ · Giới thiệu"},
  {name:"goalsTitle",label:"Tiêu đề mục tiêu",section:"Trang chủ · Mục tiêu 12 tháng"},
  ...([1,2,3,4].flatMap(i=>[{name:`goal${i}Value`,label:`Chỉ số ${i}`,section:"Trang chủ · Mục tiêu 12 tháng"},{name:`goal${i}Label`,label:`Mô tả chỉ số ${i}`,section:"Trang chủ · Mục tiêu 12 tháng"}]) as AdminField[]),
  {name:"ecosystemTitle",label:"Tiêu đề hệ sinh thái",section:"Trang chủ · Hệ sinh thái"},{name:"ecosystemBody",label:"Mô tả hệ sinh thái",type:"textarea",section:"Trang chủ · Hệ sinh thái"},
  {name:"aboutImage",label:"Ảnh không gian CIIC",type:"image",section:"Trang chủ · Không gian"},{name:"spaceTitle",label:"Tiêu đề không gian",section:"Trang chủ · Không gian"},{name:"spaceBody",label:"Mô tả không gian",type:"textarea",section:"Trang chủ · Không gian"},
  {name:"activitiesTitle",label:"Tiêu đề hoạt động",section:"Trang chủ · Hoạt động"},{name:"activitiesBody",label:"Mô tả hoạt động",type:"textarea",section:"Trang chủ · Hoạt động"},{name:"valuesTitle",label:"Tiêu đề giá trị",section:"Trang chủ · Giá trị"},{name:"registerTitle",label:"Tiêu đề đăng ký",section:"Trang chủ · Đăng ký"},{name:"registerBody",label:"Mô tả đăng ký",type:"textarea",section:"Trang chủ · Đăng ký"},
  {name:"primaryColor",label:"Màu xanh chính",type:"color",section:"Màu sắc"},{name:"accentColor",label:"Màu xanh đậm",type:"color",section:"Màu sắc"},{name:"backgroundColor",label:"Màu nền",type:"color",section:"Màu sắc"},{name:"textColor",label:"Màu chữ",type:"color",section:"Màu sắc"},{name:"headingColor",label:"Màu tiêu đề",type:"color",section:"Màu sắc"},
  {name:"bodyFont",label:"Font nội dung",type:"select",section:"Typography",options:["Be Vietnam Pro","Manrope","Arial","Tahoma"]},{name:"headingFont",label:"Font tiêu đề",type:"select",section:"Typography",options:["Georgia","Manrope","Be Vietnam Pro"]},{name:"bodyFontSize",label:"Cỡ chữ nội dung",type:"number",section:"Typography"},{name:"headingFontSize",label:"Cỡ tiêu đề",type:"number",section:"Typography"},
  {name:"seoTitle",label:"SEO title",section:"SEO & chia sẻ"},{name:"seoDescription",label:"SEO description",type:"textarea",section:"SEO & chia sẻ"},{name:"seoKeywords",label:"Từ khóa SEO",section:"SEO & chia sẻ"},{name:"ogImage",label:"Ảnh chia sẻ 1200 × 630",type:"image",section:"SEO & chia sẻ"},
  {name:"contact.phone",label:"Hotline",section:"Liên hệ"},{name:"contact.email",label:"Email",section:"Liên hệ"},{name:"contact.address",label:"Địa chỉ",type:"textarea",section:"Liên hệ"},{name:"contact.hours",label:"Giờ hoạt động",section:"Liên hệ"},{name:"contact.facebook",label:"Facebook",type:"url",section:"Mạng xã hội"},{name:"contact.zalo",label:"Zalo",type:"url",section:"Mạng xã hội"},{name:"contact.tiktok",label:"TikTok",type:"url",section:"Mạng xã hội"},{name:"contact.youtube",label:"YouTube",type:"url",section:"Mạng xã hội"},{name:"contact.mapUrl",label:"Google Maps",type:"url",section:"Liên hệ"}
];
export default async function AdminSettingsPage(){const settings=await getSettings();return <><div className="admin-page-heading"><div><span>CIIC Tân Sơn Nhất</span><h1>Cấu hình website</h1><p>Quản lý nhận diện, nội dung trang chủ, SEO và thông tin liên hệ.</p></div></div><AdminManager collection="settings" fields={fields} initialItems={[settings as unknown as Record<string,unknown>]} singleton/></>}
