import Image from "next/image";
import Link from "next/link";
import { CiicRegistrationForm } from "@/components/site/ciic-registration-form";
import { ScrollReveal } from "@/components/site/scroll-reveal";
import { SiteFooter } from "@/components/site/footer";
import { CiicHeader } from "@/components/site/ciic-header";
import { getGallery, getPosts, getServices, getSettings } from "@/lib/content";

export const revalidate=3600;
const activities=[["Hằng ngày","Trưng bày sản phẩm, trải nghiệm sáng tạo, học tập và sinh hoạt cộng đồng."],["Hằng tuần","Acoustic Tuesday, Comedy Wednesday, Movie Night Thursday, Vibe-up Friday và Family Sunday."],["Theo mùa","Lễ hội văn hóa quốc tế, âm nhạc, ẩm thực, Trung Thu, Giáng Sinh, Tết và CIIC Birthday Bash."]];

export default async function HomePage(){
  const [settings,services,posts,gallery]=await Promise.all([getSettings(),getServices(),getPosts(),getGallery()]);
  return <div className="ipf-site"><ScrollReveal/>
    <CiicHeader settings={settings}/>
    <main>
      <section className="ipf-hero"><Image src={settings.heroImage} alt="Không gian CIIC Tân Sơn Nhất" fill priority sizes="100vw"/><div className="ipf-hero-shade"/><div className="ipf-container ipf-hero-copy"><p>{settings.heroEyebrow}</p><h1><span className="ipf-title-line">Văn hóa là nền tảng</span><em className="ipf-title-line">Sáng tạo là động lực</em></h1><span>{settings.heroSubtitle}</span><div><a className="ipf-button gold" href="#about">KHÁM PHÁ CIIC</a><a className="ipf-button ghost" href="#register">ĐĂNG KÝ THAM GIA</a></div></div></section>
      <section className="ipf-route-bar"><div className="ipf-container">{[["01","NGƯỜI DÂN","Khám phá hoạt động & ưu đãi","#register"],["02","DOANH NGHIỆP / CLB","Đăng chương trình & kết nối B2B","#register"],["03","ĐỐI TÁC","Đồng hành & phát triển dự án","#register"],["04","LỊCH HOẠT ĐỘNG","Xem trải nghiệm sắp diễn ra","#activities"]].map(([n,t,s,h])=><a href={h} key={n}><b>{n}</b><span>{t}<small>{s}</small></span></a>)}</div></section>
      <section className="ipf-section ipf-intro" id="about"><div className="ipf-container ipf-split"><div><p className="ipf-kicker">GIỚI THIỆU CIIC TÂN SƠN NHẤT</p><h2>{settings.aboutTitle}</h2></div><div><p className="ipf-lead">{settings.aboutBody}</p><p>Tận dụng hạ tầng hiện hữu để hình thành hệ sinh thái Văn hóa — Nghệ thuật — Giáo dục — Thể thao — Ẩm thực — Công nghệ — Sáng tạo.</p><a className="ipf-more" href="#values">XEM GIÁ TRỊ MÔ HÌNH →</a></div></div></section>
      <section className="ipf-goals" id="goals"><div className="ipf-container"><p className="ipf-kicker light">{settings.goalsTitle}</p><div className="ipf-goal-grid">{[[settings.goal1Value,settings.goal1Label],[settings.goal2Value,settings.goal2Label],[settings.goal3Value,settings.goal3Label],[settings.goal4Value,settings.goal4Label]].map(([v,l])=><div key={v}><b>{v}</b><span>{l}</span></div>)}</div></div></section>
      <section className="ipf-section" id="ecosystem"><div className="ipf-container"><div className="ipf-title-row"><div><p className="ipf-kicker">HỆ SINH THÁI ĐA NGÀNH</p><h2><span className="ipf-title-line">Một điểm đến</span><em className="ipf-title-line">Nhiều trải nghiệm</em></h2></div><p>{settings.ecosystemBody}</p></div><div className="ipf-ecosystem">{services.slice(0,8).map((item,i)=><article key={item.slug}><span>{String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.excerpt}</p><a href="#register">TÌM HIỂU →</a></article>)}</div></div></section>
      <section className="ipf-space" id="spaces"><div className="ipf-container"><div className="ipf-space-copy"><p className="ipf-kicker light">KHÔNG GIAN CIIC</p><h2><span className="ipf-title-line">Sáng tạo — Bản sắc</span><span className="ipf-title-line">Lan tỏa cộng đồng</span></h2><p>{settings.spaceBody}</p><div className="ipf-space-tags"><span>Văn hóa nghệ thuật</span><span>Ẩm thực</span><span>Sân khấu đa năng</span><span>Studio sáng tạo</span></div></div><div className="ipf-space-image"><Image src={settings.aboutImage} alt="Không gian văn hóa nghệ thuật CIIC" fill sizes="(max-width:900px) 100vw, 56vw"/></div></div></section>
      <section className="ipf-section ipf-activities" id="activities"><div className="ipf-container"><div className="ipf-title-row"><div><p className="ipf-kicker">HOẠT ĐỘNG & SỰ KIỆN</p><h2><span className="ipf-title-line">Thường xuyên</span><em className="ipf-title-line">Đa dạng — Liên tục</em></h2></div><p>{settings.activitiesBody}</p></div><div className="ipf-activity-list">{activities.map(([label,title],i)=><article key={label}><b>0{i+1}</b><div><small>{label}</small><h3>{title}</h3></div><a href="#register">ĐĂNG KÝ →</a></article>)}</div><div className="ipf-program-cards" id="events">{gallery.slice(0,3).map((item,i)=><article key={item._id||item.title}><span>{item.category||["CỘNG ĐỒNG","SÁNG TẠO","GIAO THƯƠNG"][i]}</span><h3>{item.title}</h3><p>{item.description}</p><a href="#register">QUAN TÂM CHƯƠNG TRÌNH →</a></article>)}</div></div></section>
      <section className="ipf-gallery-section"><div className="ipf-container"><div className="ipf-title-row"><div><p className="ipf-kicker light">HÌNH ẢNH & TRẢI NGHIỆM</p><h2><span className="ipf-title-line">Khám phá CIIC</span><span className="ipf-title-line">qua từng không gian</span></h2></div><p>Hình ảnh mô phỏng và hoạt động thực tế được quản lý trực tiếp trong Kho ảnh admin.</p></div><div className="ipf-gallery-mosaic">{gallery.slice(0,6).map((item,i)=><figure className={`tile-${i+1}`} key={item._id||item.title}><Image src={item.image} alt={item.title} fill sizes="(max-width:700px) 100vw, 50vw"/><figcaption><small>{item.category}</small><b>{item.title}</b></figcaption></figure>)}</div></div></section>
      <section className="ipf-values" id="values"><div className="ipf-container"><p className="ipf-kicker light">GIÁ TRỊ CỘNG ĐỒNG</p><h2>{settings.valuesTitle}</h2><div className="ipf-value-grid">{[["Địa phương","Lắng nghe ý kiến, giới thiệu lịch hoạt động và cùng xây dựng những chương trình thiết thực."],["Doanh nghiệp — CLB","Giới thiệu thương hiệu, kết nối hợp tác và đưa sản phẩm đến gần cộng đồng."],["Cộng đồng — Thành viên","Không gian học tập, thể thao, văn hóa, việc làm, kỹ năng và khởi nghiệp."],["Kết nối rộng mở","Chia sẻ cách làm hiệu quả để những hoạt động ý nghĩa có thể lan tỏa đến nhiều nơi."]].map(([t,p],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
      <section className="ipf-section ipf-news" id="news"><div className="ipf-container"><div className="ipf-title-row"><div><p className="ipf-kicker">TRUNG TÂM THÔNG TIN</p><h2>Cập nhật mới</h2></div><a className="ipf-more" href="#register">NHẬN THÔNG TIN →</a></div><div className="ipf-news-grid">{posts.slice(0,3).map(post=><article key={post.slug}><div className="ipf-news-image"><Image src={post.image} alt={post.title} fill sizes="(max-width:800px) 100vw, 33vw"/></div><small>{post.publishedAt}</small><h3>{post.title}</h3><p>{post.excerpt}</p><Link href={`/${post.slug}`}>ĐỌC THÊM →</Link></article>)}</div></div></section>
      <section className="ipf-register" id="register"><div className="ipf-container ipf-split"><div><p className="ipf-kicker light">THAM GIA HỆ SINH THÁI</p><h2><span className="ipf-title-line">Cùng CIIC</span><span className="ipf-title-line">kiến tạo</span><em className="ipf-title-line">một điều mới</em></h2><p>{settings.registerBody}</p><ul><li>Người dân & thành viên cộng đồng</li><li>Doanh nghiệp, CLB, hội đoàn</li><li>Nhà trường, chuyên gia và đối tác quốc tế</li></ul></div><CiicRegistrationForm/></div></section>
    </main>
    <SiteFooter settings={settings} services={services} />
  </div>;
}
