import Link from "next/link";

export const revalidate = 300;
const programs = [["12.10.2026","WORKSHOP","Tư duy đổi mới trong kỷ nguyên AI","09:00 — 11:30"],["25.10.2026","NETWORKING","CIIC Open House: Kết nối hệ sinh thái","14:00 — 17:00"],["08.11.2026","INCUBATION","Gọi hồ sơ chương trình Ươm tạo 2027","Đăng ký trước ngày 30.11.2026"]];

export default function HomePage() {
  return <>
    <div className="ciic-top"><div className="ciic-wrap"><span>TRUNG TÂM ĐỔI MỚI SÁNG TẠO CÔNG NGHIỆP VIỆT NAM</span><span>Hotline: <b>028 7304 1730</b> &nbsp;|&nbsp; VI / EN</span></div></div>
    <header className="ciic-nav"><div className="ciic-wrap ciic-nav-inner"><Link className="ciic-brand" href="/"><span className="ciic-logo">CIIC</span><span>TÂN SƠN NHẤT<small>ĐỔI MỚI SÁNG TẠO</small></span></Link><nav><a href="#about">GIỚI THIỆU</a><a href="#ecosystem">HỆ SINH THÁI</a><a href="#programs">CHƯƠNG TRÌNH</a><a href="#contact">LIÊN HỆ</a></nav><Link className="ciic-btn" href="#contact">ĐĂNG KÝ KẾT NỐI ↗</Link></div></header>
    <main>
      <section className="ciic-hero"><div className="ciic-wrap ciic-hero-inner"><div><p className="ciic-eyebrow">CIIC TÂN SƠN NHẤT · HỒ CHÍ MINH</p><h1>Nơi những<br/><em>ý tưởng</em> cất cánh</h1><p className="ciic-lead">Không gian kết nối đổi mới sáng tạo, công nghệ và nguồn lực để cùng kiến tạo những giá trị bền vững cho Việt Nam.</p><div className="ciic-actions"><Link className="ciic-btn" href="#about">KHÁM PHÁ CIIC ↓</Link><Link className="ciic-text-link" href="#programs">Xem chương trình →</Link></div></div><div className="ciic-seal">CIIC<br/><small>2026</small></div></div></section>
      <section className="ciic-section ciic-wrap" id="about"><p className="ciic-kicker">01 / VỀ CHÚNG TÔI</p><div className="ciic-two"><h2>Một nền tảng<br/><span>cho tương lai</span></h2><div><p className="ciic-large">CIIC Tân Sơn Nhất là điểm hội tụ của doanh nghiệp, startup, nhà đầu tư, chuyên gia và cộng đồng đổi mới sáng tạo.</p><p>Chúng tôi kiến tạo môi trường mở để thử nghiệm ý tưởng, chia sẻ tri thức và kết nối nguồn lực — từ một cuộc gặp nhỏ đến những bước tiến lớn.</p><Link className="ciic-text-link" href="#contact">Tìm hiểu thêm ↗</Link></div></div></section>
      <section className="ciic-stats"><div className="ciic-wrap ciic-stat-grid"><div><b>01</b><span>Không gian<br/>kết nối</span></div><div><b>360°</b><span>Hệ sinh thái<br/>đổi mới</span></div><div><b>24/7</b><span>Sẵn sàng<br/>đồng hành</span></div><div><b>∞</b><span>Tiềm năng<br/>phát triển</span></div></div></section>
      <section className="ciic-section ciic-wrap" id="ecosystem"><p className="ciic-kicker">02 / HỆ SINH THÁI</p><div className="ciic-two"><h2>Kết nối để<br/><span>cùng tiến xa</span></h2><p>Khám phá các lớp dịch vụ được thiết kế cho từng hành trình phát triển.</p></div><div className="ciic-cards">{[["01","Không gian","làm việc","Văn phòng, phòng họp và không gian sự kiện linh hoạt cho mọi quy mô."],["02","Ươm tạo &","tăng tốc","Chương trình hỗ trợ startup biến ý tưởng thành sản phẩm có tác động."],["03","Kết nối","đầu tư","Mở rộng cơ hội hợp tác giữa doanh nghiệp, nhà đầu tư và chuyên gia."]].map(([num,a,b,text],i)=><article className={`ciic-card ciic-card-${i}`} key={num}><small>{num}</small><strong>{i===0?'◌':i===1?'✦':'◎'}</strong><h3>{a}<br/>{b}</h3><p>{text}</p><Link href="#contact">Khám phá ↗</Link></article>)}</div></section>
      <section className="ciic-programs" id="programs"><div className="ciic-wrap"><p className="ciic-kicker ciic-light">03 / CHƯƠNG TRÌNH NỔI BẬT</p><div className="ciic-two"><h2>Chương trình<br/><span>đang diễn ra</span></h2><Link className="ciic-outline" href="#contact">XEM TẤT CẢ ↗</Link></div><div className="ciic-timeline">{programs.map(([date,tag,title,time])=><article key={date}><time>{date}</time><div><small>{tag}</small><h3>{title}</h3><p>{time}</p></div><b>↗</b></article>)}</div></div></section>
      <section className="ciic-quote ciic-wrap"><b>“</b><blockquote>Đổi mới sáng tạo không bắt đầu từ một công nghệ. Nó bắt đầu từ một câu hỏi đúng và những người cùng nhau đi tìm câu trả lời.</blockquote><p>— CIIC Tân Sơn Nhất</p></section>
      <section className="ciic-contact" id="contact"><div className="ciic-wrap ciic-two"><div><p className="ciic-kicker ciic-light">04 / KẾT NỐI VỚI CIIC</p><h2>Hãy bắt đầu<br/><em>một điều mới</em></h2><p>Bạn có ý tưởng, dự án hoặc nhu cầu hợp tác? Đội ngũ CIIC sẵn sàng lắng nghe.</p></div><div className="ciic-form"><label>HỌ VÀ TÊN<input placeholder="Nhập họ và tên"/></label><label>EMAIL / SỐ ĐIỆN THOẠI<input placeholder="email@domain.com"/></label><label>BẠN QUAN TÂM ĐIỀU GÌ?<select><option>Không gian làm việc</option><option>Ươm tạo & tăng tốc</option><option>Hợp tác / đầu tư</option><option>Tham gia sự kiện</option></select></label><button className="ciic-btn">GỬI YÊU CẦU ↗</button></div></div></section>
    </main>
    <footer className="ciic-footer"><div className="ciic-wrap ciic-footer-grid"><div className="ciic-brand"><span className="ciic-logo">CIIC</span><span>TÂN SƠN NHẤT<small>ĐỔI MỚI SÁNG TẠO</small></span></div><div><b>CIIC TÂN SƠN NHẤT</b><p>Đổi mới sáng tạo cho một Việt Nam phát triển.</p></div><div><b>LIÊN HỆ</b><p>12A Trường Sơn, Tân Bình<br/>TP. Hồ Chí Minh<br/>hello@ciic.vn</p></div><div><b>THEO DÕI</b><p>Facebook · Instagram<br/>LinkedIn · YouTube</p></div></div><div className="ciic-wrap ciic-copy">© 2026 CIIC Tân Sơn Nhất. All rights reserved.</div></footer>
  </>;
}
