import mongoose from "mongoose";
const uri=process.env.MONGODB_URI;if(!uri)throw new Error("Thiếu MONGODB_URI");
await mongoose.connect(uri,{dbName:process.env.MONGODB_DB||"ciic"});
const settings={siteName:"Trung tâm Đổi mới sáng tạo Công nghiệp Văn hóa Tân Sơn Nhất",shortName:"CIIC Tân Sơn Nhất",slogan:"Văn hóa là nền tảng · Sáng tạo là động lực",logoUrl:"/images/ciic/logo.jpeg",heroImage:"/images/ciic/image90.png",aboutImage:"/images/ciic/image68.png",technologyImage:"/images/ciic/image92.png",ogImage:"/images/ciic/image90.png",heroEyebrow:"Trung tâm Đổi mới sáng tạo Công nghiệp Văn hóa",heroTitle:"Văn hóa là nền tảng — Sáng tạo là động lực",heroSubtitle:"Mô hình mẫu văn hóa số cấp cơ sở tại Tân Sơn Nhất.",aboutTitle:"Từ một cơ sở hiện hữu đến điểm mẫu công nghiệp văn hóa số",aboutBody:"Nơi người dân học tập, sinh hoạt, sáng tạo, thụ hưởng và kết nối doanh nghiệp ngay tại địa phương.",servicesHeroTitle:"Hệ sinh thái đa ngành",servicesHeroSubtitle:"Văn hóa, nghệ thuật, giáo dục, thể thao, ẩm thực, công nghệ và sáng tạo.",servicesHeroCta:"Đăng ký tham gia hệ sinh thái",servicesClosingTitle:"Cùng CIIC kiến tạo giá trị mới",servicesClosingBody:"Kết nối Chính quyền, Hiệp hội, Doanh nghiệp, Nhà trường, CLB và Người dân.",seoTitle:"CIIC Tân Sơn Nhất | Trung tâm Đổi mới sáng tạo Công nghiệp Văn hóa",seoDescription:"Mô hình mẫu trung tâm đổi mới sáng tạo công nghiệp văn hóa cấp cơ sở tại 446–448 Hoàng Văn Thụ, TP.HCM.",seoKeywords:"CIIC Tân Sơn Nhất, công nghiệp văn hóa, đổi mới sáng tạo, văn hóa số",primaryColor:"#006548",accentColor:"#003f35",backgroundColor:"#ffffff",textColor:"#173b34",headingColor:"#003f35",bodyFont:"Be Vietnam Pro",headingFont:"Georgia",bodyFontSize:16,headingFontSize:68,contact:{phone:"079 8888 558",email:"",address:"446–448 Hoàng Văn Thụ, P. Tân Sơn Nhất, TP.HCM",hours:"Đang cập nhật",facebook:"",zalo:"",tiktok:"",tiktokDoctor:"",youtube:"",mapUrl:"https://www.google.com/maps/search/?api=1&query=446-448+Hoang+Van+Thu+Tan+Son+Nhat+Ho+Chi+Minh"}};
const services=[
["Không gian văn hóa — nghệ thuật","khong-gian-van-hoa-nghe-thuat","Trải nghiệm bản sắc Việt qua biểu diễn, hội họa, triển lãm và hoạt động tương tác.","/images/ciic/image68.png"],
["Cộng đồng học tập & sáng tạo","cong-dong-hoc-tap-sang-tao","Chương trình giáo dục, kỹ năng, nghề nghiệp, khởi nghiệp và sáng tạo trẻ.","/images/ciic/image92.png"],
["Triển lãm — hội chợ — giao thương","trien-lam-hoi-cho-giao-thuong","Trưng bày sản phẩm, phiên chợ, hội nghị, kết nối B2B và xúc tiến thương mại.","/images/ciic/image104.png"]].map(([title,slug,excerpt,image],i)=>({title,slug,excerpt,description:excerpt,image,icon:"sparkle",order:i+1,featured:true,published:true}));
const posts=[
["CIIC Tân Sơn Nhất — mô hình mẫu công nghiệp văn hóa cấp cơ sở","ciic-tan-son-nhat-mo-hinh-mau","Tận dụng hạ tầng hiện hữu để hình thành hệ sinh thái văn hóa, sáng tạo và công nghệ.","/images/ciic/image90.png"],
["Hệ sinh thái đa ngành tại CIIC","he-sinh-thai-da-nganh-ciic","Từ giáo dục, nghệ thuật, thể thao đến studio nội dung số, ẩm thực và kinh tế đêm.","/images/ciic/image94.png"],
["Hoạt động thường xuyên cho mọi đối tượng","hoat-dong-thuong-xuyen-ciic","Chương trình hằng ngày, cuối tuần và lễ hội theo mùa dành cho cộng đồng.","/images/ciic/image128.png"]].map(([title,slug,excerpt,image])=>({title,slug,excerpt,content:excerpt,image,publishedAt:"2026-10-07",published:true}));
await mongoose.connection.collection("settings").updateOne({},{$set:settings},{upsert:true});
for(const item of services)await mongoose.connection.collection("services").updateOne({slug:item.slug},{$set:item},{upsert:true});
for(const item of posts)await mongoose.connection.collection("posts").updateOne({slug:item.slug},{$set:item},{upsert:true});
console.log("Đã khởi tạo dữ liệu CIIC.");await mongoose.disconnect();
