import {notFound} from "next/navigation";
import Link from "next/link";
import mongoose from "mongoose";
import {AdminManager,type AdminField} from "@/components/admin/manager";
import {connectToDatabase} from "@/lib/db";
const state:AdminField[]=[{name:"status",label:"Trạng thái",type:"select",options:[{value:"draft",label:"Bản nháp"},{value:"review",label:"Chờ duyệt"},{value:"published",label:"Đã xuất bản"},{value:"hidden",label:"Tạm ẩn"},{value:"ended",label:"Đã kết thúc"}]},{name:"published",label:"Hiển thị công khai",type:"checkbox"},{name:"order",label:"Thứ tự",type:"number"}];
const configs:Record<string,{title:string;fields:AdminField[]}>= {
 categories:{title:"Danh mục",fields:[{name:"name",label:"Tên danh mục"},{name:"slug",label:"Đường dẫn"},{name:"parentId",label:"Mã danh mục cha"},{name:"description",label:"Mô tả",type:"textarea"},{name:"image",label:"Ảnh",type:"image"},...state]},
 activities:{title:"Hoạt động & lớp học",fields:[{name:"name",label:"Tên hoạt động"},{name:"slug",label:"Đường dẫn"},{name:"categoryId",label:"Mã danh mục"},{name:"venueIds",label:"Mã địa điểm"},{name:"organizerId",label:"Mã đơn vị tổ chức"},{name:"description",label:"Giới thiệu",type:"textarea"},{name:"ageGroup",label:"Độ tuổi"},{name:"level",label:"Cấp độ"},{name:"capacity",label:"Sức chứa",type:"number"},{name:"price",label:"Chi phí",type:"number"},{name:"registrationEnabled",label:"Mở đăng ký",type:"checkbox"},{name:"image",label:"Ảnh 16:9",type:"image"},...state]},
 venues:{title:"Địa điểm",fields:[{name:"name",label:"Tên địa điểm"},{name:"slug",label:"Đường dẫn"},{name:"address",label:"Địa chỉ"},{name:"mapUrl",label:"Bản đồ",type:"url"},{name:"capacity",label:"Sức chứa",type:"number"},{name:"amenities",label:"Tiện ích",type:"textarea"},{name:"sportTypes",label:"Hoạt động phù hợp"},{name:"image",label:"Ảnh",type:"image"},...state]},
 resources:{title:"Sân, phòng & thiết bị",fields:[{name:"name",label:"Tên tài nguyên"},{name:"slug",label:"Đường dẫn"},{name:"venueId",label:"Mã địa điểm"},{name:"type",label:"Loại"},{name:"capacity",label:"Sức chứa",type:"number"},{name:"price",label:"Giá",type:"number"},{name:"unit",label:"Đơn vị tính"},{name:"rules",label:"Nội quy",type:"textarea"},{name:"image",label:"Ảnh",type:"image"},...state]},
 schedules:{title:"Lịch hoạt động",fields:[{name:"title",label:"Tên lịch"},{name:"activityId",label:"Mã hoạt động"},{name:"eventId",label:"Mã sự kiện"},{name:"venueId",label:"Mã địa điểm"},{name:"resourceId",label:"Mã sân/phòng"},{name:"startAt",label:"Bắt đầu"},{name:"endAt",label:"Kết thúc"},{name:"capacity",label:"Sức chứa",type:"number"},{name:"status",label:"Tình trạng",type:"select",options:[{value:"draft",label:"Bản nháp"},{value:"open",label:"Đang mở"},{value:"full",label:"Đủ chỗ"},{value:"cancelled",label:"Đã hủy"},{value:"completed",label:"Đã kết thúc"}]},{name:"note",label:"Ghi chú",type:"textarea"}]},
 events:{title:"Sự kiện & giải đấu",fields:[{name:"title",label:"Tên sự kiện"},{name:"slug",label:"Đường dẫn"},{name:"venueId",label:"Mã địa điểm"},{name:"organizerId",label:"Mã đơn vị tổ chức"},{name:"startAt",label:"Bắt đầu"},{name:"endAt",label:"Kết thúc"},{name:"deadline",label:"Hạn đăng ký"},{name:"capacity",label:"Sức chứa",type:"number"},{name:"price",label:"Lệ phí",type:"number"},{name:"description",label:"Nội dung",type:"textarea"},{name:"image",label:"Ảnh",type:"image"},...state]},
 organizers:{title:"Đơn vị tổ chức",fields:[{name:"name",label:"Tên đơn vị"},{name:"slug",label:"Đường dẫn"},{name:"type",label:"Loại hình"},{name:"contactName",label:"Người liên hệ"},{name:"phone",label:"Điện thoại"},{name:"email",label:"Email"},{name:"address",label:"Địa chỉ"},{name:"description",label:"Giới thiệu",type:"textarea"},{name:"image",label:"Logo/ảnh",type:"image"},...state]},
 bookings:{title:"Booking",fields:[{name:"code",label:"Mã booking"},{name:"name",label:"Người đặt"},{name:"phone",label:"Điện thoại"},{name:"email",label:"Email"},{name:"resourceId",label:"Mã sân/phòng"},{name:"venueId",label:"Mã địa điểm"},{name:"startAt",label:"Bắt đầu"},{name:"endAt",label:"Kết thúc"},{name:"participants",label:"Số người",type:"number"},{name:"message",label:"Ghi chú",type:"textarea"},{name:"status",label:"Tình trạng",type:"select",options:[{value:"pending",label:"Chờ xác nhận"},{value:"confirmed",label:"Đã xác nhận"},{value:"waitlist",label:"Danh sách chờ"},{value:"completed",label:"Hoàn thành"},{value:"cancelled",label:"Đã hủy"}]}]},
 registrations:{title:"Đăng ký hoạt động",fields:[{name:"code",label:"Mã đăng ký"},{name:"name",label:"Họ tên"},{name:"phone",label:"Điện thoại"},{name:"email",label:"Email"},{name:"activityId",label:"Mã hoạt động"},{name:"eventId",label:"Mã sự kiện"},{name:"scheduleId",label:"Mã lịch"},{name:"participants",label:"Số người",type:"number"},{name:"status",label:"Tình trạng",type:"select",options:[{value:"pending",label:"Chờ xác nhận"},{value:"confirmed",label:"Đã xác nhận"},{value:"waitlist",label:"Danh sách chờ"},{value:"completed",label:"Hoàn thành"},{value:"cancelled",label:"Đã hủy"}]}]},
};
const keys=Object.keys(configs);export function generateStaticParams(){return keys.map(collection=>({collection}));}
export default async function Page({params}:{params:Promise<{collection:string}>}){const {collection}=await params;const config=configs[collection];if(!config)notFound();const connected=await connectToDatabase();const items=connected?JSON.parse(JSON.stringify(await mongoose.connection.collection(collection).find({}).sort({createdAt:-1}).toArray())):[];return <><div className="admin-page-heading"><div><span>Vận hành CIIC</span><h1>{config.title}</h1><p>Quản lý dữ liệu vận hành theo đề án CIIC.</p></div></div><nav className="admin-operation-tabs">{keys.map(key=><Link className={key===collection?"active":""} href={`/admin/operations/${key}`} key={key}>{configs[key].title}</Link>)}</nav><AdminManager collection={collection} fields={config.fields} initialItems={items}/></>}
